version: "3.8"

services:
  node:
    ports:
      - 8181:8181
    build:
      context: .
      dockerfile: dockerfiles/node.dockerfile
    extra_hosts:
      - "domain.test:127.0.0.1"
    volumes:
      - ./src:/app
      - /app/node_modules
    networks:
      - node

  mariadb_skats_positivliste:
    image: "mariadb:lts"
    ports:
      - "3306:3306"
    env_file:
      - ./env/mariadb-skats-positivliste.env
    volumes:
      - db_skats_positivliste:/var/lib/mysql
    networks:
      - database
      - node

volumes:
  db_skats_positivliste:

networks:
  node:
    name: "node_network"
  database:
    name: "database_network"
